package com.illusionman1212.lyricsgrabbr.ui.theme

import androidx.compose.ui.graphics.Color

//val Purple80 = Color(0xFFD0BCFF)
//val PurpleGrey80 = Color(0xFFCCC2DC)
//val Pink80 = Color(0xFFEFB8C8)
//
//val Purple40 = Color(0xFF6650a4)
//val PurpleGrey40 = Color(0xFF625b71)
//val Pink40 = Color(0xFF7D5260)
//
//val ColorSecondaryLight = Color(0xFF999999)

val ColorPrimaryLight = Color(0xFFFFFFFF)
val ColorPrimaryVariantLight = Color(0xFFEFEFEF)
val ColorOnPrimaryLight = Color(0xFF000000)
val ColorSecondaryLight = Color(0xFF999999)
val ColorSecondaryVariantLight = Color(0xFF888888)
val ColorOnSecondaryLight = Color(0xFF111111)
val ColorAmoledLight = Color(0xFFFFFFFF)

val ColorPrimaryDark = Color(0xFF222222)
val ColorPrimaryVariantDark = Color(0xFF202020)
val ColorOnPrimaryDark = Color(0xFFFFFFFF)
val ColorSecondaryDark = Color(0xFF696969)
val ColorSecondaryVariantDark = Color(0xFF515151)
val ColorOnSecondaryDark = Color(0xDFFFFFFF)
val ColorAmoledDark = Color(0xFF000000)

val md_theme_light_primary = Color(0xFF7C44A8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFF2DAFF)
val md_theme_light_onPrimaryContainer = Color(0xFF2E004D)
val md_theme_light_secondary = Color(0xFF675A6E)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFEEDDF5)
val md_theme_light_onSecondaryContainer = Color(0xFF221829)
val md_theme_light_tertiary = Color(0xFF99405F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9E1)
val md_theme_light_onTertiaryContainer = Color(0xFF3F001C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1D1B1E)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1D1B1E)
val md_theme_light_surfaceVariant = Color(0xFFEADFEA)
val md_theme_light_onSurfaceVariant = Color(0xFF4B454D)
val md_theme_light_outline = Color(0xFF7C757E)
val md_theme_light_inverseOnSurface = Color(0xFFF6EFF3)
val md_theme_light_inverseSurface = Color(0xFF322F33)
val md_theme_light_inversePrimary = Color(0xFFE1B6FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF7C44A8)
val md_theme_light_outlineVariant = Color(0xFFCDC3CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFE1B6FF)
val md_theme_dark_onPrimary = Color(0xFF4B0A76)
val md_theme_dark_primaryContainer = Color(0xFF632A8E)
val md_theme_dark_onPrimaryContainer = Color(0xFFF2DAFF)
val md_theme_dark_secondary = Color(0xFFD2C1D9)
val md_theme_dark_onSecondary = Color(0xFF372C3F)
val md_theme_dark_secondaryContainer = Color(0xFF4E4256)
val md_theme_dark_onSecondaryContainer = Color(0xFFEEDDF5)
val md_theme_dark_tertiary = Color(0xFFFFB1C6)
val md_theme_dark_onTertiary = Color(0xFF5E1131)
val md_theme_dark_tertiaryContainer = Color(0xFF7B2947)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9E1)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1D1B1E)
val md_theme_dark_onBackground = Color(0xFFE7E1E5)
val md_theme_dark_surface = Color(0xFF1D1B1E)
val md_theme_dark_onSurface = Color(0xFFE7E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF4B454D)
val md_theme_dark_onSurfaceVariant = Color(0xFFCDC3CE)
val md_theme_dark_outline = Color(0xFF968E98)
val md_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val md_theme_dark_inverseSurface = Color(0xFFE7E1E5)
val md_theme_dark_inversePrimary = Color(0xFF7C44A8)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFE1B6FF)
val md_theme_dark_outlineVariant = Color(0xFF4B454D)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF662D91)